import './style.css';
const anime=[
 {id:'solstice',name:'Solstice Requiem',type:'TV',year:'2024',score:'9.2',eps:'12 episodes',genre:'Fantasy · Drama',image:'https://images.unsplash.com/photo-1519608487953-e999c86e745c?auto=format&fit=crop&w=900&q=85',desc:'When the last city beneath a violet sky begins to forget the sun, an unlikely pair follows a song through the endless night.'},
 {id:'glass',name:'Glass Horizon',type:'Movie',year:'2025',score:'8.8',eps:'1h 47m',genre:'Sci-Fi · Mystery',image:'https://images.unsplash.com/photo-1534447677768-be436bb09401?auto=format&fit=crop&w=900&q=85',desc:'A cartographer finds impossible coastlines appearing in the clouds above her quiet island.'},
 {id:'bloom',name:'Bloom After Rain',type:'TV',year:'2024',score:'8.5',eps:'24 episodes',genre:'Romance · Slice of Life',image:'https://images.unsplash.com/photo-1497250681960-ef046c08a56e?auto=format&fit=crop&w=900&q=85',desc:'Two strangers rebuild a neglected greenhouse, one rainy afternoon at a time.'},
 {id:'astra',name:'Astra Noir',type:'TV',year:'2023',score:'8.7',eps:'18 episodes',genre:'Action · Thriller',image:'https://images.unsplash.com/photo-1446776811953-b23d57bd21aa?auto=format&fit=crop&w=900&q=85',desc:'The detective who can read starlight must solve a murder beyond the orbit of Mars.'},
 {id:'paper',name:'Paper Moons',type:'Manga',year:'2025',score:'9.0',eps:'38 chapters',genre:'Coming of age',image:'https://images.unsplash.com/photo-1494438639946-1ebd1d20bf85?auto=format&fit=crop&w=900&q=85',desc:'A magical realist journey about letters, memory, and the moon that carries them.'}
];
const $=s=>document.querySelector(s); let state={theme:localStorage.getItem('theme')||'dark',lite:false,query:''}; document.documentElement.dataset.theme=state.theme;
function icon(n){return `<span class="ico">${n}</span>`}
function nav(){return `<header><a class="brand" href="#/">yume<span>kai</span><i></i></a><nav><a href="#/" data-n="home">Discover</a><a href="#/search" data-n="search">Browse</a><a href="#/community" data-n="community">Community</a><a href="#/library" data-n="library">Library</a></nav><div class="head-actions"><button class="round" id="quickSearch">⌕</button><button class="round" id="theme">☼</button><a href="#/profile" class="avatar">KA</a></div></header>`}
function card(a,rank){return `<a class="card" href="#/anime/${a.id}"><div class="cover" style="background-image:linear-gradient(0deg,rgba(13,13,18,.55),transparent 58%),url('${a.image}')">${rank?`<b class="rank">${rank}</b>`:''}<span class="score">★ ${a.score}</span></div><h3>${a.name}</h3><p>${a.type} · ${a.year}</p></a>`}
function shell(content){$('#app').innerHTML=nav()+`<main>${content}</main><div class="mobile-nav"><a href="#/">⌂<small>Home</small></a><a href="#/search">⌕<small>Browse</small></a><a href="#/community">♧<small>Social</small></a><a href="#/library">▱<small>Library</small></a></div>`;bindBase()}
function home(){shell(`<section class="hero"><div class="hero-image"></div><div class="hero-copy"><span class="eyebrow">ORIGINAL · NEW EPISODE</span><h1>Make your<br><em>world</em> a story.</h1><p>Solstice Requiem is now streaming. Watch the season finale with your people.</p><div class="actions"><a class="button" href="#/watch/solstice">▶ Watch now</a><a class="button ghost" href="#/anime/solstice">＋ Add to list</a></div><div class="hero-meta">★ 9.2 <i></i> 2024 <i></i> 16+</div></div><div class="watching"><span class="live-dot"></span> 2,418 watching together</div></section><section class="section-head"><div><span class="eyebrow">CURATED FOR YOU</span><h2>Keep exploring</h2></div><a href="#/search">View all →</a></section><section class="rail">${anime.slice(1).map(card).join('')}</section><section class="split"><div><span class="eyebrow">FROM THE COMMUNITY</span><h2>The characters we can't stop thinking about</h2><p>Join 1.8k fans discussing the spring season's most unforgettable moments.</p><a class="text-link" href="#/community">Enter the conversation →</a></div><div class="thread-preview"><div class="face">M</div><div><b>mika.jpg</b><p>That final rooftop scene... I need a minute.</p><small>184 replies · 20 min ago</small></div><button>♡ 1.4k</button></div></section>`) }
function search(){let q=state.query;let filtered=anime.filter(x=>x.name.toLowerCase().includes(q.toLowerCase())||x.genre.toLowerCase().includes(q.toLowerCase()));shell(`<section class="browse"><span class="eyebrow">FIND YOUR NEXT OBSESSION</span><h1>Browse <em>stories</em></h1><label class="searchbar">⌕<input autofocus placeholder="Search anime, manga, characters..." value="${q}"></label><div class="chips"><button class="active">All</button><button>Anime</button><button>Manga</button><button>Trending</button><button>Recently updated</button></div><div class="results-title"><h2>${q?`Results for “${q}”`:'Trending now'}</h2><span>${filtered.length} titles</span></div><div class="grid">${filtered.map(card).join('')||'<p>No stories found. Try another search.</p>'}</div></section>`);$('.searchbar input').oninput=e=>{state.query=e.target.value;search()}}
function detail(id){let a=anime.find(x=>x.id===id)||anime[0];shell(`<section class="detail-hero" style="--bg:url('${a.image}')"><div class="detail-art"></div><div class="detail-info"><span class="eyebrow">${a.type.toUpperCase()} · ${a.year}</span><h1>${a.name}</h1><div class="stats"><b>★ ${a.score}</b><span>${a.eps}</span><span>HD</span><span>SUB | DUB</span></div><p>${a.desc}</p><div class="tags"><b>${a.genre.split(' · ').join('</b><b>')}</b></div><div class="actions"><a class="button" href="#/watch/${a.id}">▶ Start watching</a><button class="button ghost save">＋ Save</button></div></div></section><section class="detail-body"><div><div class="section-head"><div><span class="eyebrow">SEASON 01</span><h2>Episodes</h2></div><button class="select">English (US)⌄</button></div><div class="episodes">${[1,2,3,4,5,6].map((n)=>`<a href="#/watch/${a.id}" class="episode"><span>${String(n).padStart(2,'0')}</span><div><b>${['The Quiet Before','City of No Tomorrow','A Map of Stars','What We Remember','The Longest Night','Sunrise'][n-1]}</b><small>24 min · Sub & Dub</small></div><i>›</i></a>`).join('')}</div></div><aside class="side-card"><span class="eyebrow">YOUR PROGRESS</span><h3>Not started</h3><div class="progress"><i></i></div><p>Save this title to sync progress across devices.</p><button class="button full save">＋ Add to library</button></aside></section>`) }
function watch(id){let a=anime.find(x=>x.id===id)||anime[0];shell(`<section class="watch-layout"><div><a class="back" href="#/anime/${a.id}">← Back to details</a><div class="player" style="background-image:linear-gradient(0deg,rgba(0,0,0,.75),transparent),url('${a.image}')"><button class="play" id="play">▶</button><div class="controls"><b>Ⅱ</b><div class="timeline"><i></i></div><span>08:42 / 24:06</span><button>⚙</button><button>⛶</button></div></div><div class="watch-title"><div><span class="eyebrow">S1 E1 · THE QUIET BEFORE</span><h2>${a.name}</h2></div><button class="round save">＋</button></div><div class="options"><button>☷ Subtitles: English</button><button>◉ Quality: Auto</button><button>♬ Audio: Japanese</button><button>☾ Background play</button></div></div><aside class="chat"><div class="chat-head"><b><span class="live-dot"></span> Watch together</b><small>58 people here</small></div><div class="messages"><p><b>kairo</b> this opening never gets old</p><p><b>luna</b> the colors are incredible ✦</p><p><b>ren.exe</b> here we go!</p></div><label><input placeholder="Say something..."><button>↑</button></label><a href="#/community" class="room-link">Open room & chat →</a></aside></section>`) }
function community(){shell(`<section class="community"><span class="eyebrow">THE YUMEVERSE</span><h1>Better with <em>friends.</em></h1><p>Make lists. Start a room. Find your people.</p><div class="community-grid"><article class="feature-tile purple"><span>◌  LIVE NOW</span><h2>Friday night<br>rewatch club</h2><p>97 fans are watching Astra Noir.</p><a href="#/watch/astra">Join room →</a></article><article class="feature-tile orange"><span>♜  COMMUNITY RANKING</span><h2>Spring 2025<br>tier list</h2><p>4,219 votes · 3 days left</p><a href="#/search">Cast your vote →</a></article></div><div class="section-head"><div><span class="eyebrow">TRENDING THREADS</span><h2>On your feed</h2></div><a href="#/community">See all →</a></div><div class="threads">${['The little details that made Solstice Requiem hit different','What manga are you reading this weekend?','Drop your comfort anime below ☁'].map((x,i)=>`<article><div class="face">${['A','N','Y'][i]}</div><div><b>${['akira','noa','yumi'][i]} <small>· ${i+1}h</small></b><h3>${x}</h3><p>♡ ${[482,264,891][i]} &nbsp; ◌ ${[64,38,122][i]} replies</p></div><button>•••</button></article>`).join('')}</div></section>`) }
function library(){shell(`<section class="library"><span class="eyebrow">YOUR SPACE</span><h1>Your <em>library</em></h1><div class="sync"><div><b>Keep your story in sync</b><p>Connect AniList or MyAnimeList to bring your lists and progress home.</p></div><button class="button" id="connect">Connect account</button></div><div class="tabs"><b>Watching</b><span>Plan to watch</span><span>Completed</span><span>Playlists</span></div><div class="empty">✦<h2>Your next story awaits</h2><p>Save titles to keep track of everything you love.</p><a class="button" href="#/search">Explore titles</a></div></section>`) }
function profile(){shell(`<section class="profile"><div class="profile-top"><div class="avatar big">KA</div><div><span class="eyebrow">@KAIRO</span><h1>Kai’s corner</h1><p>night owl · sci-fi enthusiast · always reading</p></div><button class="button ghost">Edit profile</button></div><div class="profile-stats"><b>24 <small>following</small></b><b>312 <small>followers</small></b><b>86 <small>titles</small></b></div><section class="section-head"><h2>Recent activity</h2></section><div class="activity">Finished <b>Bloom After Rain</b> · rated it ★ 9</div></section>`) }
function bindBase(){let r=location.hash.split('/')[1]||'';document.querySelector(`[data-n="${r||'home'}"]`)?.classList.add('selected');$('#theme').onclick=()=>{state.theme=state.theme==='dark'?'light':'dark';document.documentElement.dataset.theme=state.theme;localStorage.theme=state.theme};$('#quickSearch').onclick=()=>location.hash='/search';document.querySelectorAll('.save').forEach(x=>x.onclick=()=>{x.textContent='✓ Saved';x.classList.add('saved')});$('#connect')?.addEventListener('click',()=>{let x=$('#connect');x.textContent='Connected ✓';x.classList.add('saved')});$('#play')?.addEventListener('click',e=>{e.target.textContent=e.target.textContent==='▶'?'Ⅱ':'▶'})}
function route(){let p=location.hash.slice(2).split('/');if(p[0]==='anime')detail(p[1]);else if(p[0]==='watch')watch(p[1]);else ({search,community,library,profile}[p[0]]||home)()}window.onhashchange=route;route();
